main: me.codalot.gui.MenuLib
name: MenuLib
version: 1.0

api-version: 1.13

author: Shoham Tzubery (SirCodlaot)
website: https://github.com/SirCodalot/MenuLib
description: An opensource library for making animated and configurable Minecraft menus

commands:
  menulib:
    description: Load and open menus.
    aliases: [mlib, menulibrary]